---
title: "Data visualization"
author: "Elise Gonzales"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
library(janitor)

#wrappers around ggplot
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)
library(gapminder)
#library(sf)
```

###Read in lizard data    
```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))
```

###Basic ggplot - point
```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point()
```

##Histogram
```{r}
ggplot(data = lizards, aes(x = total_length)) +
  geom_histogram(color = "purple",
                 fill = "orange",
                 size = 1,
                 linetype = "dotted") #sturgis rule? to figure out reasonable # of bins to accurately represent distribution of data
```

```{r}
ggplot(data = lizards,
       aes(x = total_length, y = weight)) +
         geom_point(
           shape = 24,
           color = "cyan4",
           fill = "chartreuse")
```

##map based on variables
```{r}
ggplot(data = lizards,
       aes(x = total_length, 
           y = weight)) +
  geom_point(aes(color = common_name, 
                 size = total_length), alpha = 0.5) + theme_minimal()
```

##facet
```{r}
ggplot(data = lizards,
       aes(x = total_length, 
           y = weight)) + 
  geom_point() +
  facet_wrap(~common_name)
```

###Re-order
```{r}
lizard_counts <- lizards |> 
  group_by(common_name) |> 
  summarize(counts = n())

#same thing
lizards_total <- lizards |> 
  count(common_name, site, tail) #you can add these extra variables in group_by() too
```

##Column/bar graph, re-order
```{r}
ggplot(data = lizard_counts, 
       aes(y = fct_reorder(common_name, counts), x = counts)) + geom_col()

#convert to factor to specify which order to display variables in, instead of default alphabetical

```

Create scatterplots, faceted by species, for total length vs weight. Color & shape of points should differ based on common_name. Change theme. Make each faceted panel have flexible axes limits. Scale should be free
```{r}
ggplot(data = lizards,
       aes(x = total_length, 
           y = weight)) + 
  geom_point(aes(color = common_name, 
                 shape = common_name,
             alpha = 0.6,
             size = 1)) +
  facet_wrap(~common_name, scales = "free") +
  theme_linedraw() +
  labs(x = "Total length (mm)",
       y = "Weight (g)") +
  title = "Jornada Basin lizard sizes" +
  subtitle = "All lizards follow the standard length-weight relationship, with Western Whiptails being largest" +
  caption = "Data: Jornada Basin LTER, CCBY"
```

